### ISSUE TITLE
Endpoint for new maven repositories

### ISSUE THREAD

**Issue by mme** [cdklabs/jsii-release#251]
The endpoint for new maven repositories is now:

https://s01.oss.sonatype.org

This means for new maven repositories:
- ```MAVEN_ENDPOINT``` must be set to ```https://s01.oss.sonatype.org```, otherwise jsii-release-maven will fail with a "403 Forbidden" error
- to get the "Staging profile ID", one has to log in at https://s01.oss.sonatype.org, not at https://oss.sonatype.org

Thought this would be useful to mention in the docs.

**Comment by eladb** [comment]
Absolutely. Contributions are welcome!

**Comment by mme** [comment]
Ok, sent you a pull request.
